# Generated by Django 4.1.9 on 2023-05-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
